function setup() {
  // get the slider object from the HTML:
  var slider = document.getElementById('confidence');
  // add an event listener for the slider:
  slider.addEventListener('change', judgeMe, false);
}

function judgeMe() {
  // this function was generated by an event.
  // the event has a target, i.e. the slider you interacted with
  // that object has a value:
  var confidenceValue = event.target.value;
  // get the message div from the HTML so you can change its text:
  var messageDiv = document.getElementById('judgement');

  // set the message div text using the slider value:
  messageDiv.innerHTML = confidenceValue;

  // judge the user based on his or her confidence,
  // and add to the message div accordingly:
  if (confidenceValue < 10) {
    messageDiv.innerHTML += "% You're really guessing, aren't you?";
  }

  if (confidenceValue >= 10 && confidenceValue < 30) {
    messageDiv.innerHTML += "% What are you basing that on?";
  }

  if (confidenceValue >= 30 && confidenceValue < 60) {
    messageDiv.innerHTML += "% There are probably data to support that...";
  }

  if (confidenceValue >= 60 && confidenceValue < 99) {
    messageDiv.innerHTML += "% That seems pretty solid...";
  }

  if (confidenceValue === 100 ) {
    messageDiv.innerHTML += "% That's a fact, Jack.";
  }
}

// this runs when this script is loaded. This script
// is linked at the end of the HTML doc, so it's loaded
// once the HTML doc loads:
setup();
